name: PublishToGHPackages
on: [push]

env:
  VERSION: $(ruby -r ./lib/fiat_stripe/version.rb -e "print(FiatStripe::VERSION)")

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Sets the runner to Ruby 2.6
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    
    # Create cache layer
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    
    - name: Install SQLite
      run: sudo apt-get install libsqlite3-dev
    
    - name: Bundle Install
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    
    # Build the gem locally to the runner working directory
    - name: Build locally
      run: |
        gem build fiat_stripe.gemspec
    
    # Credential file is used to authenticate to GitHub Packages
    - name: Create credential file 
      run: |
        if [[ ! -d "~/.gem" ]]; then
          mkdir ~/.gem
        fi
        echo ":github: Bearer ${{ secrets.GITHUB_TOKEN }}" >> ~/.gem/credentials
        chmod 600 ~/.gem/credentials

    # Pushes the previously-built gem to GitHub Packages
    - name: Publish to GitHub Packaages
      run: |
        gem push --key github --host https://rubygems.pkg.github.com/fiatinsight fiat_stripe-${{ env.VERSION }}.gem